### ISSUE TITLE
[ScatterPlot] Radius not set in Firefox

### ISSUE THREAD

**Issue by RaoOfPhysics** [explorable-viz/fluid#1023]
Problem is with setting SVG circle radius property `r` via CSS, which is supported in Chrome but not Firefox.

- [x] Define `ScatterPlotHelpers` with `point_attrs` function similar to `LineChartHelpers`
- [x] Add additional `ScatterPlotHelpers` argument to `drawScatterPlot` (analogous to `drawLineChart`) and adjust `ScatterPlot.js` to account for the extra argument:
  - [x] add initial argument `lineChartHelpers` to `drawScatterPlot_` (see `drawLinePlot_` for an example)
  - [x] adjust the `export var drawScatterPlot` at the bottom to account for extra arg (again see `LinePlot.js`)
- [x] Remove obsolete CSS  

See also:
- #583 

***

As of https://github.com/explorable-viz/fluid/commit/fe5d91d2f3b19d48973a076d3f75aaf3a7175e3d

This is `/renewables`:

![Screenshot 2024-07-05 at 11-50-41 Fluid Data-Linked Visualisations](https://github.com/explorable-viz/fluid/assets/7623019/209b190a-cadd-45e5-aca1-31184fa777ef)

And this is on the main page (`127.0.0.1:8080/`):

![Screenshot 2024-07-05 at 11-52-52 Fluid Data-Linked Visualisations](https://github.com/explorable-viz/fluid/assets/7623019/54523790-2076-48ce-8491-8e76ebed6d9b)

The issue seems to be from the canvas? See `<g>` in the code:

![Screenshot_20240705_120113](https://github.com/explorable-viz/fluid/assets/7623019/51c9cbae-6cc2-4da6-afae-3ab1b7c5aefb)

**Comment by rolyp** [comment]
@hanaizakim @ColinC-UoE You can also start checking off the subtasks above (and adding new subtasks, e.g. remove obsolete CSS and retest.)
