### ISSUE TITLE
Replace `rm -rf` by `rimraf` in Node scripts

### ISSUE THREAD

**Issue by hanaizakim** [explorable-viz/fluid#1025]
Our Node scripts in `package.json` contain some non-portable shell commands.

on clone: make yarn install include chromeheadless & npm-run-all & rimraf

- [ ] Change `rm -rf` to `rimraf`
- [ ] Change `mkdir` to `mkdirp`
- [ ] `npm install –save-dev rimraf mkdirp`
- [ ] Split “Software required” section of `README.md` into 2 sections (Windows, Linux/Mac)

**Comment by rolyp** [comment]
Thanks @hanaizakim @ColinC-UoE. Updating the issue description with a few additional subtasks.

**Comment by rolyp** [comment]
Aborted, decided that Windows development will only be supported inside Linux subsystem. There were a bunch of annoying issues in addition to `rm -rf`, e.g. spaces inside file paths, single quotes vs. escaped double quotes, but even with those worked around we had problems with `spago build`.
