### ISSUE TITLE
NPM library

### ISSUE THREAD

**Issue by RaoOfPhysics** [explorable-viz/fluid#1036]
- [x] Organisation account on https://www.npmjs.com with @hanaizakim, @ColinC-UoE & @rolyp as users
- [x] NPM package called `fluid-lang`
- [x] Script in `package.json` to publish to NPM
- [x] Complete metadata in `package.json`
- [x] Test by `yarn add fluid-lang` into a fresh Node project
- [x] Test via `yarn add @explorable-viz/fluid` and then `yarn install`
- [x] Publish from `release` only
   - [x] Workflow files `build.yml` and `deploy.yml`
      - [x] `build` triggers on `workflow_call`
      - [x] `deploy` triggers on `push`; publish to NPM if `build` succeeds, and pushes to GitHub if publish to NPM succeeds

See also:
- #1057
- #1018 

***
Right now, to make a Fluid publication, we have to clone the whole `explorable-viz/fluid` repo and then create HTML files and more within it. We would like to move to a modular approach where the development of the language is decoupled from publication mechanisms.

For now, we will set up separate repos for generated documents (starting with a minimal HTML page etc.). GitHub Actions will be used to build the website associated with each independent repo, using the HTML file.

To use `fluid`, at the moment will have to use `git submodule`. And we will need to have a `.purs` file with all the Fluid modules and data for analysis in addition to the HTML+CSS files. Eventually these will be migrated as follows:

- `git submodule` for Fluid &rarr; `npm` package for Fluid.
- `.purs` file specifying Fluid modules and analysis data &rarr; `.yml` file with this information.

—

Related to https://github.com/explorable-viz/fluid-examples/discussions/10

**Comment by rolyp** [comment]
Rescoping this task to “npm library” (because at that point it becomes moot what the contents of this repo include).

**Comment by rolyp** [comment]
Hi @ColinC-UoE, some notes for today:
- In the spirit of continuous integration, let’s get the `deploy-npm` part of this task merged to `develop`. I guess that means changing `if: github.ref == ‘refs/heads/creating-NPM-library’` to use `release` (although when testing you’ll need to switch it back locally). Merge `develop` again into your branch and do a PR on your branch in GitHub. 
- Then you can close this issue - I’ve pulled the “command-line tool” part into a fresh task as it’s starting to feel quite separate.

**Comment by rolyp** [comment]
Hi @ColinC-UoE. Looks like you closed this but haven’t yet merged to `develop` – it looks like there are some conflicts, so probably best to fix those, do the merge and only then mark the task as done.
