### ISSUE TITLE
Avoid rebuild on changes to `.fld` files

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#1064]
At the moment, need to rebuild the entire project every time we want to refresh the files for `serve-app`. This is a hassle when just updating fluid files when testing user features in the app.

- [x] Eliminate redundancy between `refresh-app` and `clean-app`
- [x] Rename `refresh-app` to `copy-static`

**Comment by JosephBond** [comment]
Closed by https://github.com/explorable-viz/fluid/pull/1065,

If you update your fluid code, call `yarn refresh-app` and `yarn serve-app` then refresh your page.

**Comment by rolyp** [comment]
Reopened as failing in GitHub Actions workflow.
