### ISSUE TITLE
`LineChart` tick placement

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1066]
- [x] Naive first pass: add tick for every _x_ value for which we have a data element (See more general suggestion below)
- [x] `LineChart` to specify image size (initially unused)
  - [x] Add `size` field to `LineChart`
  - [x] Renaming for consistency (check `DataType.purs` too):
    - [x] `ScatterPlot.data` to `points`
    - [x] `BarChart.data` to `stackedBars`
    - [x] `LinePlot.data` to `points` 
    - [x] `Primitive.record2` to `record`
- [x] Replace hardcoded constant `image` by `size`
- [x] Duplicated _x_ tick labels
- [x] Try bigger image for `Methane` example
- [x] Examples/tests that share `.fld` source _code_ to share source _files_ instead
  - [x] Delete `linked-outputs/stacked-bar-chart-scatter-plot.fld` (duplicate)
  - [x] Delete `linked-outputs/bar-chart-line-chart.fld` (duplicate)
- <s>Detect whether _x_ tick widths are wider than available space?</s>
  - <s>Separate construction of _x_ and _y_ axes (because width of x-axis ticks determines length of y-axis)?</s>
 - [x] Tick configuration options: 
   - <s>`NumTicks` or `DataValues`? </s> :x: maybe later
   - [x] `Orientation` (either `Default` or `Rotated`) 

***
Line chart ticks are always separated by the integer 1, which generally performs pretty badly:

<img src="https://github.com/user-attachments/assets/de69710e-f835-4322-8e6c-a071a16f579b" width="400">

We can probably implement a heuristic that performs as expected when individual line plots are uniform and share a frequency, and performs “reasonably” when the line plots have different x-axis frequencies or have missing or irregular data points.

See also:
- [ChatGPT discussion](https://chatgpt.com/share/c4b2d705-e99d-45bc-995e-2af4c502756a) on possible solutions to various kinds of input sequence

**Comment by rolyp** [comment]
@RaoOfPhysics I’ve made some basic generalisations/improvements that address this to a degree sufficient for the “methane” example. In particular:

- The y-axis now places a tick if that y-coordinate occur in any of the individual line plots. This is a fairly naive heuristic but reasonable as a first pass. 
- `LineChart` must now specify the overall size of the image. This allows the user to allocate more real estate if the legend is large, which will shrink the amount of horizonal space available for the chart, and thus make the y-axis more dense.
- The user must also supply one of `Default` or `Rotated` for each axis, to specify whether the tick labels are to be rotated by 45 degrees or not.

The effect of these combined allows for a decent presentation of the “methane” example, e.g. picking `Rotated` for the y-axis ticks and an image width of 450 seems to work well. 

Later we can think about further generalisation/consolidation. For example the x-axis currently always has exactly three ticks, unlike the y axis which uses the procedure mentioned above; we could expose those as user options instead.

**Comment by RaoOfPhysics** [comment]
Should I pull `develop` or `experiment`, please?

**Comment by RaoOfPhysics** [comment]
Ah, `experiment` no longer exists. Will pull `develop`.

**Comment by rolyp** [comment]
Hi @RaoOfPhysics. I’ve just merged `develop` to `temp-relative-paths` – I think that may be the one you need for the file URLs to resolve correctly.

**Comment by RaoOfPhysics** [comment]
Looks great in Chrome! <3 Still kinda broken in Firefox, but that is a different matter.

![Screenshot 2024-09-25 at 14-16-53 Re-implementation of IPCC data in Fluid](https://github.com/user-attachments/assets/8861aa22-053c-4431-89cd-876cfe1c21ec)
