### ISSUE TITLE
Example referring to bars in bar charts

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1106]
We have some really nice examples from the IPCC AR6 Summary for Policy Makers of text that refers in non-trivial ways to visualisations, e.g. referring common substructure shared by a bunch of bar charts. Mock this up in Fluid (not necessarily using real data, at least initially) to start to tease out some of the issues that come up.

A key idea here is that **selecting text** computed from a subcomponent of a visualisation induces a **selection on the subcomponent**. This is a new use case for us, as we haven't yet treated a visualisation as an input to a later stage in the computation. There may be some implied changes to the (currently rather simplistic) `Fig` setup.

See also:
- explorable-viz/fluid#1118
- #270

**Comment by rolyp** [comment]
@JosephBond Added a new issue to mock up some of that figure from the IPCC Summary for Policymakers. Something to look at maybe next week once the doc draft is in better shape and the record/dict refactoring is out of the way.

**Comment by rolyp** [comment]
@JosephBond Bumped to In Progress

**Comment by JosephBond** [comment]
Closing under explorable-viz/transparent-text#5
