### ISSUE TITLE
IPCC AR6: Table SPM.1

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#1118]
We have a nice example now from the IPCC AR6 Summary for Policymakers which we can adapt/grow into a substantial worked example.
 
- [x] Change title on html page
- [x] Remove table from output multiview
- [ ] Import into working document (perhaps as appropriately-styled LaTeX rather than images?)
- [x] Inline `to` and `from` fields to avoid issue with nested data (for now)
- [x] `likelihoodMap` as table rather than function
- [ ] Include `°C` for temperature values
- [ ] Library function for generically selecting rows/columns from lists of records (implemented as dictionaries)
- [ ] Examples illustrating how (intentionally or otherwise) “wrong” code could be more visible in our system:
  - [ ] `1.4` refering to different quantity than suggested by the text
  - [ ] Scenario given one name but referring to different data set

See also:
- explorable-viz/fluid-examples#38
- explorable-viz/fluid-examples#49
- explorable-viz/fluid#1115
- explorable-viz/fluid#1076
- explorable-viz/fluid#1114

Done/dropped:
- [x] Example of text with references to numerical quantities and quantitative/graded phrases
  - [x] Maybe with summary table and references to elements of table?
- [x] Example of text that refers to images as well
- [x] Example from IPCC report of attempt to quantify graded adverbs

***
We need to find some examples of text that can be used to sketch out the types of text we might want to synthesize.

As a start, the use of specific terminology in the IPCC report for policymakers, the authors set the scene by clearly marking what certain terminology means in terms of probability.
![ipcc-probabilities](https://github.com/user-attachments/assets/6f51a45d-26d6-422b-be0f-d87f0fd7e403)

**Comment by JosephBond** [comment]
From later in the same section, we see the following text which quantifies the report-writers confidence in human-caused global temperature increase:
![ipcc-temp-increase](https://github.com/user-attachments/assets/a6d413ad-2a16-40a3-b4c3-e8295bb3744c)

3 questions raised by the screenshotted text
1. What exactly do the phrases _likely_,_very likely_, and _extremely likely_ link to in this context? The data used to compute the probabilities, the mapping from probability values to words (as in the nombre example), or both?
2. Is it best to start with reports on large scale data analysis, such as environmental data science? My intuition is that the class of text we want to generate should be informed by the relationships that it can be linked against if we have the goal of transparency
3. For the references at the end of the main paragraph, do we just want to make those interactive links to the figures/sections in general? If so, do we need to account for that somehow in our dependency relation

**Comment by JosephBond** [comment]
In reports like the IPCC SPM (summary for policy makers) report, we often see reference made to visual elements directly within the text, referring both to elements of graphs, and to the graphs themselves.

![ippc-visual-elements](https://github.com/user-attachments/assets/9ccbac2c-710f-4170-937e-558a44cdc95e)


In the attached image, I've highlighted a few of the types of visual element that may be referenced in text, such as graphs or entire panels in black. The text highlighted in the red rectangle creates an implicit scope for all text after it, now every reference to a visual element will refer to 5 things in the figure, which we highlight with red arrows instead of black ones

**Comment by JosephBond** [comment]
The above example is paired with a table. If we allow ourselves to change the text associated with it partially, we can use the table in 2 ways:
1. Directly reference values in the table, for example the fact that the best estimate of global temperature increase at the end of the 21st century will be less than 2.0C for the 2 best-case situations presented elsewhere in the report
2. Talk about the values of the total heating bars indirectly, by referring to the rest of the best-estimate values in the table all at once. Could combine that with distributed language like the red highlighted text in bars above.
![ipcc-table-explanation](https://github.com/user-attachments/assets/b23294e1-c8f0-4518-be35-91bc963f4bfb)

To do so might require our ability to attach confidence intervals to bars, maybe those could be tuples of numbers attached to bars sent to a bar chart.

**Comment by rolyp** [comment]
Hi @JosephBond. Added some subtasks as per discussion yesterday.

**Comment by rolyp** [comment]
Renamed from “Illustrative text fragments” – let’s use this to track the new IPCC example.

**Comment by rolyp** [comment]
Migrating to the `fluid` repo (we can create a new task to write up the example in `transparent-text`).

**Comment by JosephBond** [comment]
Interpreting the text (B.1.2) under Table SPM.1 is somewhat more complex than it initially appeared. My current interpretation is that the first part of the paragraph : 
```
Based on the assessment of multiple lines of evidence, global warming of 2°C, relative to 1850–1900, would be exceeded
during the 21st century under the high and very high GHG emissions scenarios considered in this report (SSP3-7.0 and
SSP5-8.5, respectively). Global warming of 2°C would extremely likely be exceeded in the intermediate GHG emissions
scenario (SSP2-4.5). Under the very low and low GHG emissions scenarios, global warming of 2°C is extremely unlikely
to be exceeded (SSP1-1.9) or unlikely to be exceeded (SSP1-2.6).
```
is referring to the "long term" estimates in Table SPM.1, meanwhile the second half of the paragraph
```
Crossing the 2°C global warming level in the mid-
term period (2041–2060) is very likely to occur under the very high GHG emissions scenario (SSP5-8.5), likely to occur
under the high GHG emissions scenario (SSP3-7.0), and more likely than not to occur in the intermediate GHG emissions
scenario (SSP2-4.5).
```
Is referring to the data situation in the medium term period. With this understanding, I believe that we must construct these "extremely likely"'s etc twice for each scenario, once for the medium term data, and once for the long term data

**Comment by JosephBond** [comment]
Worried I'm wasting time on this, but this example is seeming to me to be quite difficult to make work, esp in comparison to the barchart

**Comment by rolyp** [comment]
I think just prioritise the things (from both examples) that are either important fixes or relatively low-hanging fruit, and leave anything more difficult until those are dealt with.

**Comment by JosephBond** [comment]
Closing as subsumed by explorable-viz/transparent-text#26
