### ISSUE TITLE
Forward projectional slicing

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#284]
We’ll do forward slicing first as we can manage without a trace for that.

- typing:
  - [x] type annotation on the variable in a `VarElim` (and probably the variable in a `Let`)
  - [x] function `typeOf`, relying on the type annotations, which assigns a unique type to a term
  - [x] extend `typeOf` to assign a unique type slice to a term slice
  - [x] define `typeOf` for values as well (maybe add a `Typed` type class)
- slice forms for:
  - [x] types
  - <s>environments</s>
  - [x] values (not closures yet)
  - [x] expressions (not functions yet)
  - <s>eliminators</s>
- forward slicing for:
  - [x] evaluation
  - [x] pattern matching
  - <s>environment lookup</s>
- [x] free variables of an expression
- [x] `proj` function which projects a sliced term/value/type to a non-sliced one

**Comment by rolyp** [comment]
@min-nguyen This is what we’ll talk about tomorrow.

**Comment by rolyp** [comment]
@min-nguyen I’ve closed the other task as complete. Could you add the photos from today to this task?

My suggestion would be to start with the typing function, since we’ll need type assignments and type slices to sanity-checking slicing. I think the single type annotation on the parameter of an `ElimVar` should be enough to do this, but let me know if you hit any difficulties.

**Comment by rolyp** [comment]
I’ve also added a GitHub action that builds and tests the PureScript code on every push to `master`.

**Comment by min-nguyen** [comment]
![89740892_226130588577339_7422667020451184640_n](https://user-images.githubusercontent.com/22860381/76630613-3c273d80-6538-11ea-811c-2a61f8d158f6.jpg)
![89687355_2963229283700345_538103043627941888_n](https://user-images.githubusercontent.com/22860381/76630623-434e4b80-6538-11ea-9ad4-d0211486f0bc.jpg)
![89778049_515096055722276_5491436126856019968_n](https://user-images.githubusercontent.com/22860381/76630628-447f7880-6538-11ea-9e40-4894c9743bdc.jpg)

**Comment by min-nguyen** [comment]
I'm wondering, what's a clear way to express slice syntax (underlined expressions)

**Comment by rolyp** [comment]
Good question. I think we’ll probably have to use the name of the constructor to indicate the part of the term that is being projected out. For example, considering expressions:
```purescript
data Expr = Num Int 
          | Var Var
          | True
          | False
          | Pair Expr Expr
          | Pair_Fst Expr
          | Pair_Snd Expr
          | Nil 
          | Cons Expr Expr
          | Cons_Head Expr
          | Cons_Tail Expr
          | Let Var Expr Expr
          | Let_Body Expr
          | Match Expr Elim
          | Func Elim
          | App Expr Expr
          | App_Fun Expr
          | Add Expr Expr
```
This might get a bit verbose, so we might at the same time want to consider whether using a module idiom might allow us to drop the `Expr-` prefix on every constructor. (I’ve assumed this in the code above.)

Note how forms like `PairFst` don’t need to specify the component which has been discarded (in contract to what I said earlier). So we don’t need to worry about how to compute the term we want to mark as fully erased; `PairFst` just means that the second component is fully erased, along with the `Pair` constructor.

I haven’t given any slicing forms for `Match` or `Add` yet. I’ve also left out the `App1` application form we discussed earlier. We can come back to these once the basics are in place.

**Comment by rolyp** [comment]
@min-nguyen As for the question about whether a fully underlined thing can contain non-underlined things, I think the answer is no. In fact (see comment above), I’m not sure we need “underlined” things at the moment; subtrees that aren’t mentioned are implicitly fully discarded. (Like an implicit hole.) Underlining is useful in the formalism, because we are able to define a slice with respect to the term it’s a slice of. That’s not so easy in code (at least not without dependent types).

This might be clearer once we start implementing the partial order (or the meet/join operation). For example:
```purescript
join (PairFst e1) (Pair e1’ e2) = Pair (join e1 e1’) e2
join (PairSnd e2) (Pair e1 e2’) = Pair e1 (join e2 e2’)
```
i.e. forms like `PairFst` effectively have a hole where the discarded sibling is and joining a hole with `e` is always `e`.

**Comment by min-nguyen** [comment]
Can you elaborate on

- the slice forms for contexts and environments 

- how environment lookup differs when forward slicing as opposed to eval

On another note:

- I've tried separating the data types into modules, but ran into circular dependencies. I'll take a look at it another time.

- Purescript's means of instantiating Ord is a bit silly. Stating that 
```haskell
(Pair_Fst x) (Pair x y) = LT 
```
does not imply 
```haskell
(Pair x y) (Pair_Fst x)  = GT 
```

**Comment by min-nguyen** [comment]
Actually, would it be helpful for me to refer to your latex draft

**Comment by rolyp** [comment]
Yes, for the slice forms for contexts and environments, see the paper draft. I’ve also just added an explicit definition of environment lookup x: v ∈ ρ (fig. 14). I think what we want is for lookup just to “see through” an erased binding (i.e. the rule is as for a non-erased binding, but without the side-condition). For this to be monotonic, I think we need to define environment slices so that we have to slice away all occurrences of a variable that are in scope, not just the innermost one. I’ll update that definition now and ping you when it’s ready.

You can ignore the definition of “environment update” (underneath lookup) for now - we won’t need that until we come to backward slicing.

**Comment by rolyp** [comment]
@min-nguyen Ok, I’ve added a side-condition to the definition of environment slicing (Fig. 8) which requires that an environment that has been sliced to remove a binding of x must have as its tail an environment that doesn’t itself contain a binding of x. “Contains a binding of x” (x: v ∈ ρ) is a defined simultaneously with the definition of environment slice (both inductively).

**Comment by rolyp** [comment]
Actually I’ve pushed this constraint up to context slices: the side-condition on context slices requires a context which has been sliced to remove its innermost type assignment for x must also have any other type assignments for x sliced away. The side-condition I previously had on on environment slices is now implied, so I’ve deleted it.

I’ve added a sub-task to this task to define a `typeOf` function - I think this will be useful for implementing some basic sanity-checks for the slicing.

**Comment by rolyp** [comment]
@min-nguyen I’ve updated the task list above with the things that look like they’re converging on an initial pass. Next priority is probably test cases: for typing, typing in the presence of slicing, and evaluation in the presence of slicing. There should be a property like “if e evalutes to v, then the type of v is the type of e”, and that should commute with slicing.

We’ll have to rethink `TypPoly` at some point. Perhaps for now we can make do with a type annotation on `Nil`. That would be way too cumbersome in practice, but it will allow us to make progress.

**Comment by rolyp** [comment]
Better suggestion re. `TypPoly`: maybe just require `List` to be a list of `Nat` for now. That will restrict the examples we can experiment with but is probably easier than requiring a type annotation on `Nil`. The most important thing now is to have a simple toy language that we can do a full implementation of the new approach with.

I’ve added one more task to the list at the top: implementing some kind of `proj` function (what I was writing with vertical bars on the blackboard, i.e. |e|). This projects out the subprogram from e specified by the erased parts. This should also commute with typing and evaluation:

if e ⟹ v then:
   - typeOf e = typeOf v
   - proj e ⟹ proj v

and so 

   - typeOf (proj e) = typeOf (proj v)

**Comment by rolyp** [comment]
@min-nguyen The code on the `annot` branch looks like a good start. (I like the use of `α` for annotations - you could also use `ρ` for environments and `σ` for eliminators.)

The `∧` operator is meet (or conjunction in a Boolean setting), not join/disjunction. For example in the `+` rule, the output of the plus is available iff you’re in “construction” mode (the `α` argument to `eval` is true) _and_ each of the operand values is available.

I notice you’ve left out the annotations on expressions for now. That’s probably sensible for the time being. For testing, we’ll have to construct programs that run in a non-empty environment, and slice the values in the environment. That’s probably a good paradigm for us to explore first anyway.

I think it makes sense for the `ValFailure` values to be treated like any other (annotated) constant, as you’ve done.

I’ll put some examples somewhere now that we should be able to use to start exercising the new rules.

**Comment by rolyp** [comment]
Let’s start with this example, a function which simply copies a list:
```
(rec copy { Nil -> Nil, Cons(x, xs) -> Cons(x, copy xs) }) Cons(3, Cons(4, Nil))
```
If we slice away the middle cons cell of the input, by setting the annotations on the red bits below to false:
<code>
Cons(3, <b>Cons(4,</b> Nil<b>)</b>)
</code>
Then we want to the output to be sliced in the same way.

**Comment by rolyp** [comment]
Here’s another recursive example. This time we probably will want to give a `let` name to one or both of the functions, which will make the need for `letrec` more apparent. I’ll write it with the existing syntax for now.

````
let length = rec length { 
   Nil -> 0, 
   Cons(x, xs) -> 1 + length xs 
} in
let f = rec f { 
   Nil -> Nil, 
   Cons(x, xs) -> Cons(length (f xs), f xs) 
} in
f Cons(3, Cons(4, Nil))
=> Cons(1, Cons(0, Nil))
````
Now slicing the outer cons cell from the output will erase a two-hole context from the ouput (if my paper sketches are correct, which they are quite possibly not):

<code>
f <b>Cons(3,</b> Cons(4, Nil)<b>)</b>
=> <b>Cons(</b>1<b>,</b> Cons(0, Nil)<b>)</b>
</code>
<p>
<p>
(The highlighting isn't clear so you might want to look at the HTML to see which bits have been erased. I think it should be the outermost `Cons` of the output, but neither its head nor its tail.)

**Comment by rolyp** [comment]
@min-nguyen By the way, you might like to have a go at replacing recursive function literals by `letrec` in the formalism yourself - you have all the raw ingredients already. If you feel like it go ahead.

**Comment by min-nguyen** [comment]
I'm going to go and try to slice `Expr`, as in some cases (such as the copy function) which works on lists, I can't pre-manipulate the environment to annotate lists unless they've been bound to a variable already. I've done a few other tests though such as variable slicing, and everything seems to be working well so far.

**Comment by rolyp** [comment]
@min-nguyen I’ve updated the formalism with a couple of changes:
1) I’ve inlined the “raw” versions of terms, values, etc, so that annotations appear on each term constructor via than indirectly via another data type. This gives us a big more flexibility, since we no longer require every term constructor to have an annotation. In particular, at the moment I’ve left out annotations on functions, applications and `let`.
2) Variables in `let` binders and environments now have annotation - I’m not sure if we need this, so you can probably ignore this for now.
3) I added the syntax for traces, and also for “matches” (which are just a trace form for pattern-matches). We’ll need these for backward-slicing.

It might be advisable to re-clone the `fluid` repo - it’s now contained by a GitHub organisation (https://github.com/explorable-viz), which I also renamed. To preempty any possible Git confusion, I suggest cloning again.

Shall we aim to Skype again tomorrow (Friday)?

**Comment by min-nguyen** [comment]
Sure, feel free to suggest any time

**Comment by min-nguyen** [comment]
Also I can't seem to find the new formalism, where is it under?

**Comment by rolyp** [comment]
Let’s say 3pm again. I’ll send a Zoom link. Re. the new GitHub organisation, my suggestion would be as follows (so that your folder structure mirrors the organisation structure):
1) wherever you normally store your repos, create a folder called `explorable-viz`
1) in that folder: 
  a) clone the [`paper`](https://github.com/explorable-viz/paper) repo
  b) clone the [`fluid`](https://github.com/explorable-viz/fluid) repo

The new version to look at is in `paper/proj-slicing` – this no longer uses explicit annotations on terms/values but retains the idea of an “availability mode” which is either ⊤ or ⊥. When you’re slicing with ⊥, that means you’re in a runtime context in which you tried to consume a sliced value, which means can only make sliced values.

It also includes a relation called “projection” (written ↓). This is similar to the projection notation |e| we were using before, but makes explicit the fact that it is only partial. Not every sliced program or value can be projected; in particular I cannot project a sliced pair (where the pair constructor has been marked for erasure) if both components of the pair are still “available”. That’s because the result would be two subtrees without a root, which is a forest, not a tree. Well-formed slices in this system are those than can be projected.

Sorry to dump (another) version of the formalism on you. Let’s speak later.

**Comment by rolyp** [comment]
Closing this task as done. Minor changes we discussed yesterday (renaming :∈:, possibly inlining `BranchNil` and `BranchCons`) can be done as part of #294 or #293.
