### ISSUE TITLE
Prettyprinted CodeMirror views for each web demo

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#485]
Equip all our online examples with a “code view” (based on CodeMirror). There is a fairly minimal CodeMirror FFI in place, so this will probably involve building that out a bit.

- [x] Replace `codemirror-expt` div (currently commented out) with an appropriate view per example

Blocking on:
- #740 

See also:
- #743
- #742
- #605 
- #486
- #577

**Comment by JosephBond** [comment]
Each of the figures is loaded by a div with an id prefixed by "div-", so for example the linked figures are in a `<div>` with `id="fig-1"`
Beneath each figure if a set of `script` tags. For example, on line 58, we have `<script src="https:gist.github.com...></script>`

We will need to replace these with separate `div`'s as we do with `codemirror-expt`. Then we need to modify `drawFigs` (in `App/Main.purs`) to create new `EditorView`'s. We also need to modify `drawFig` (in Fig.purs) to take an `EditorView`, and add a `drawCode` call to it as well. We will also have to modify `drawLinkFig`, but we can cross that bridge when we come to it
