### ISSUE TITLE
Store “redex trail” when desugaring for backward analysis

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#576]
Given our current understanding of how to make desugarings “reversible” wherever they occur, I see no reason now not to roll out the approach with the `Sugar` constructor and `FromSugar e` and `Desugarable s e` type classes to the _current_ implementation, i.e. with the design that has the surface language as an entirely separate language and desugaring as a fully recursive procedure. 

The advantage of doing this would be the usual one: we can fully validate the “reversible desugaring” design ahead of making the move to the proposed new approach where `SExpr` nodes contain a mixture of `Expr` and `SExpr` nodes and desugaring only recurses into children of type `SExpr`. We should be able to do this with no significant changes to parser or test cases.

Initial steps (testing and committing after each step, as usual):
- [x] import `FromSugar e` and `Desugarable s e` infrastructure from `Expr2` to `Expr`
- [x] add `Sugar` constructors to `Expr`, `Elim` and `Trace`
- [x] implement `FV`, `BV`, `eval`, `match` and `pretty` for these forms as appropriate
- [x] `Sugar` case of `exprBwd` can ignore “redex trail” for now 

None of the new code should be exercised yet, but we know it type-checks. The next steps are a bit less certain, but here’s a start:

- [x] `exprFwd` to call itself indirectly via a helper `exprFwd’`, initially set to `exprFwd`
- [x] delete obsolete `reifySug’`
- [x] `reifySugar` to propagate `MayFail` and rename to `desugar`
- [x] set `exprFwd’` to `desugar` to generate `Sugar` terms
- [x] add `desugarBwd :: s a -> e a` to type class, to unwrap `Sugar` constructor
- [x] `exprBwd` to call itself via `desugarBwd`

**Comment by rolyp** [comment]
![IMG_20230314_115057](https://user-images.githubusercontent.com/121074/224995662-e8e18f50-1704-40db-9b60-a2dcaaee9ae1.jpg)

**Comment by rolyp** [comment]
@JosephBond I thought a bit more about this over the weekend and I think the current design actually supports doing the desugaring “eagerly”, i.e. at the point at which we construct the `Sugar` node. I.e. a `Sugar` node is something that represents the “contraction” of a sugar term to an `Expr`, retaining the original sugar for reversibility, but there is no need for this to be deferred to runtime. Let’s play around with the idea that a `Sugar` node contains both `s` _and_ the `e` that `s` desugars to, so that evaluation need only defer to the `e`. This would make the parser responsible for doing the desugaring to obtain the desired `e` and passing it to the `Sugar` constructor. The fwd/bwd evaluator would not invoke fwd/bwd desugaring, which would only be invoked when needed (e.g. by the debugger).

**Comment by rolyp** [comment]
@JosephBond Updated the title of this task to bring it closer to what we’re doing.

**Comment by rolyp** [comment]
@JosephBond The original task description was old enough to be mostly obsolete so I’ve pulled it out to the comment below. I also think there’s another “stable intermediate form” we should pursue which may in fact end up being the final form for now – see new task description above.

## Old task description

I’ll work separately on a formalism for this, but roughly the subtasks are:
- [x] `SExpr` terms now contain `Expr` subterms, rather than `Expr`
- [x] new `Expr` constructor to embed `SExpr` 
- [x] new evaluation rule for new `Expr` which delegates to desugaring
- [x] desugaring remains recursive, but only into `SExpr` parts
- [x] test `Parse2`
- [ ] test  `Eval2`
- [ ] `DesugarBwd` type class?
- [ ] test new `desugarBwd` code
- [x] #587
 
Performance is likely to be a significant issue, which won’t matter for debugging, but will for other interactive use, e.g. with the current visualisation UI. One idea would be to implement an “eager desugaring” transformation, and use that when a faster version is needed (see explorable-viz/debug-effects#42).

**Comment by JosephBond** [comment]
- [x] Inline `DesugarFwd` and `DesugarBwd` into `SExpr`, and use them to implement typeclass `Desugarable`
- [x] `exprFwd'` delegate to typeclass method `desugFwd`
- [x] `exprBwd'` delegate to typeclass method `desugBwd`
- [x] create `desugarBwd'`
- [x] test 1
- [x] set `expr(B|F)wd'` to use `desugar(B|F)wd'`
- [x]  test 2
