### ISSUE TITLE
Puppeteer-based testing for web app

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#583]
Use Puppeteer for enough (headless) web automation to validate some basic UI behaviour in `App` tests.

- [x] Purescript integration (so we can write Puppeteer tests in `.purs`) – call JS from PS or other way around?
- [x] Remove `benchtron` from `packages.dhall`
- [x] Install `Toppokki` and dependencies
- [x] Install typescript
- [x] Install Assert 
- [x] Get example program working
    - [x] Open website in headless browser 
    - [x] Assert content is non empty string 
    - [x] Screenshot
    - [x] Close browser 
    - [x] Graph exists
- [x] Top-level `test-puppeteer` script in `package.json` that starts web server and runs Puppeteer tests
  - [x] Use NPM package [`concurrently`](https://www.npmjs.com/package/concurrently) to run web server in parallel with Puppeteer tests and stop server afterwards
- [x] Update GitHub Actions workflow to run `test-puppeteer`
  - [x] `yarn puppeteer browsers install chrome` step (currently in `pre-push` script)
  - [x] Move Puppeteer logic into `pre-push` script for now to side-step any issues surrounding `concurrently`
  - [x] `ERR_CONNECTION_REFUSED` trying to connect to local web webserver via `node puppeteer.js`
    - [x] Validate we can connect to another known server
      - [x] Update Node version on GitHub Actions runner through `setup-node`
    - [x] Validate we cannot connect to a fake server
    - [x] Validate we can run `pre-push` locally 
  - [x] Shutdown local server with exit code 0
    - [x] Try `--kill-signal`
    - [x] Try `-k`
    - [x] Try kill commands with `-s` 
  - [x] Verify Puppeteer tests can exit with code 0
  - [x] Show that `http-shutdown` can be used to close server with exit code 0
    - [x] Use `http-shutdown` at the correct place
- [x] Serve static content from `dist/app` (but `http-serve` and `http-server` seem to be command-line only)
     - [x] Try `express-static`
- [x] Use helper functions from Util instead of Assert for testing
- [x] Uncomment `yarn build` and `yarn test` in `pre-push` (do later since instructions would take more time to run)
- [x] Remove `yarn spago install aff-promise` in `pre-push`
- [x] Use `wait for selector` to search webpage for element
    - [x] Check for `fig-4`, `fig-1`, and `fig-conv-2`
- [x] Rename `develop.yml` to `build.yml`
- [x] Inline `pre-push` script into `build.yml`
- [x] Sporadic failure `Error: Promise failed, couldn't extract JS Error or String`
  - [x] Pare back: do everything in `puppeteer.js` for now, and just try waiting for SVG to load
  - [x] Toppokki `goto` to accept extra `WaitForOptions` argument, similar to `waitForNavigation`
  - [x] `timeout` option for `goto`
  - [x] Specify longer timeout for `goto`
  - [x] `load` and `domcontentloaded` PuppeteerLifeCycleEvent options
  - [x] Add some logging to Fluid (e.g. on `loadFile`) :x: not written to console in headless mode  
  - [x] Is problem related to CodeMirror loading? :x: Doesn’t look like it
  - [x] Try waiting for `networkIdle0` :x: probably not relevant as script doesn’t access network?
  - [x] Wait for `document.readyState == complete` using `waitForFunction` :x: times out
- [x] Wait for `svg#fig-4-output` rather than `div#fig-4` (etc), i.e. SVG for chart to appear
- [x] How to see contents of JavaScript console in headless Chrome?
- [x] Document Puppeteer tests in `README.md`
    
See also:
- [Toppokki](https://github.com/justinwoo/purescript-toppokki)
- [Manually installing a PureScript library by editing `packages.dhall`](https://chatgpt.com/share/9e0a6d3a-f0da-4adb-8f02-7028c023ef7c)
- https://www.bannerbear.com/blog/how-to-run-puppeteer-with-firefox-instead-of-chrome/

**Comment by rolyp** [comment]
https://chatgpt.com/share/c6347724-248e-4c0e-888b-b84d3669d23e

**Comment by rolyp** [comment]
Hi @ColinC-UoE @hanaizakim, I’ve added a couple of subtasks above re. additional automation for running the Puppeteer tests locally and then getting them running in GitHub as part of the automated tests that run when you push.

**Comment by rolyp** [comment]
Hi @ColinC-UoE @hanaizakim, it’s probably also worth checking what version of `Node.js` we’re running in the Ubuntu 22.04 runner (which is what GitHub Actions uses). You could probably do this by adding `node --version` to the `pre-push` script and looking at the GitHub Actions console log. It could be quite an old version, e.g. 12.22 (locally I have 21.6.2). While this doesn’t seem to have been a problem so far, it could worth eliminating as a potential issue.

You can use the GitHub Action [`setup-node`](https://github.com/actions/setup-node) to install a later version of Node into the GitHub Action and could then check that `node --version` reports a different version number.

**Comment by RaoOfPhysics** [comment]
This – https://github.com/explorable-viz/fluid/issues/583#issuecomment-2245217794 – is probably useful for me too. Thanks for pointing us to `setup-node`.

**Comment by rolyp** [comment]
@hanaizakim I added a couple more tidy-up tasks that are unrelated to Puppeteer but that it probably makes sense to include along with this task. They’re quite straightforward, I’ll explain them when we speak later today.

**Comment by rolyp** [comment]
@hanaizakim Added a subtask to figure out how to see contents of JavaScript console in headless Chrome. I think we’ll probably need this to get a handle on what’s going wrong when the `waitForSelector` is failing – is the server stuck, or is it taking a long time doing something, etc.
