### ISSUE TITLE
Minor tidy-up after #586

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#587]
- [x] delete `clauseBwd_uncurried`?
- [x] `clause[Fwd/Bwd]_curried` -> `clause[Fwd/Bwd]`
- [x] delete `*.temp` and `*Temp` files
- [x] can `clausesBwd` be implemented just as `map (clausesBwd σ)`?
- [x] inline `clauseBwd` and `clauseFwd`, for closer correspondence to formalism
- [x] getting some spurious diffs; check `files.trimTrailingWhitespace` is set
- [x] swap args of `pattContBwd` (so pattern is first, as per formalism) 
- [x] sync `pattCont_record` and `pattCont_args` with `pattArgs` formalism
- [x] remove any commented-out code
- [x] remove any “checked” comments
- [x] remove any spurious vertical whitespace introduced during refactoring
- [x] ensure bwd/fwd consistent argument order (e.g. with patterns)
- [x] simplify `orElse` in line with latest formalism
- [x] link to formalism using comments (or omit when names obviously match)
- [x] clean up `bwded`, `unwrapped` in `MatchAs` case of `exprBwd`
- [x] `exprBwd` shouldn’t have both `list-comp-done` and `list-comp-last`
- [x] `pattsExprFwd` does `exprFwd`, but bwd direction handles this in `clausesBwd`

**Comment by JosephBond** [comment]
Regarding the relation between `clausesFwd` and  `pattsExprFwd` and the like, we have the following: 

- Forwards: `clausesFwd` depends on `pattsExprFwd` which depends on `clauseFwd`, with `clauseFwd` only called inside of `pattsExprFwd`, which is itself only called by `clausesFwd`.
 - In the backwards direction: `clausesBwd` depends on `clauseBwd` which depends on `pattsExprBwd`, `clauseBwd` is the only place which called `pattsExprBwd`, and `clausesBwd` is the only place which calls `clauseBwd`
