### ISSUE TITLE
Distinguish leaf traces

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#598]
Traces at the moment have several cases which are handled by the same constructor, `Trace.Const` which does not capture any information. As part of debugging implementation, these cases will need to be distinguished between, in order for traces to contain all information that is present in the original program rather then relying solely on having a value and trace pair.

This may not be strictly necessary, since a `Trace` combined with a `Val` is sufficient to reconstruct the original expression, as per `exprBwd`.

**Comment by rolyp** [comment]
No longer relevant as moving to graph approach.
