### ISSUE TITLE
Allocate fresh address for every syntax node

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#636]
After desugaring but before evaluation, some kind of imperative procedure (`mapM alloc`) which allocates a fresh address (vertex) to every term in a syntax tree (probably core language program only, initially) and stores it in the term, producing an expression of type `Expr (a × Vertex)`. (Where `a` is the annotation type.)

**Comment by min-nguyen** [comment]
In `Expr (a × Bool)`, is `a` the address?

**Comment by rolyp** [comment]
I think I meant `Vertex` instead of `Bool`, so `a` should actually be the (current) annotation type (concretely `Bool`), and the address is the `Vertex`. (Updated the issue description to match.)

Maybe we don’t need to think about keeping the annotation type: maybe there are two completely separate pipelines, one which takes our `Expr Unit` (produced by desugaring) and turns it into `Expr Bool` (or `Expr a` for some `Ann a =>`), and then runs the current `eval`, and other which takes an `Expr Unit` and turns it into an `Expr Vertex` and then runs the new `eval`. (I was imagining storing both on the same `Expr` but perhaps there’s no need.)

**Comment by min-nguyen** [comment]
Thanks. What do you imagine the (Bounded)Lattice implementation for addresses (vertices) as? 

edit: oh it's an empty type class

**Comment by rolyp** [comment]
@min-nguyen At the moment I think we can probably skip that generality and compute directly with concrete sets. Conceivably we might want something more general in the future (e.g. to compute vectors of slices simultaneously) but we do that generalisation as and when needed.

**Comment by min-nguyen** [comment]
Okay - I asked mainly to make Vertex an instance of `Ann`, and hence `Highlightable` and `BoundedLattice`

**Comment by rolyp** [comment]
Ah, ok. If we wanted to do that, it would be `Set Vertex` rather than `Vertex`, and $\vee$ / $\wedge$ would be $\cap$ / $\cup$ and $\top$ would be $\varnothing$ (notice how the order inverts). But this doesn’t seem to be an abstraction we need at the moment.

**Comment by min-nguyen** [comment]
I'm wondering how the setting of the annotation type actually occurs. I notice `erase` applies the `Unit` annotation to an entire program; whereas the function `eval` takes a top-level annotation e.g. `true` which it applies to the entire program,  thus implicitly setting the annotation types of the expr and env.

```purescript
testWithSetup :: File -> String -> Maybe (Selector × File) -> Aff (Env 𝔹 × S.Expr 𝔹) -> Test Unit
testWithSetup (File file) expected v_expect_opt setup =
   before setup $
      it file \(γ × s) -> do
         let
            -- Desugar surface expression to core expression, of arbitrary annotation type
            e     = successful (desugFwd' s)
            -- Evaluate the core expression e (annotated with bot) under environment γ, producing a trace and annotated value
            t × v = successful (eval γ e bot)

            -- Either a custom annotated output (from a file), or the default program output annotated with bot
            v' = fromMaybe identity (fst <$> v_expect_opt) v
            -- Use the annotated output, and backward evaluate the unannotated core expression + environment, producing an annotated core expression + environment.
            { γ: γ', e: e' } = evalBwd (erase <$> γ) (erase e) v' t
            s' = desugBwd' e' :: S.Expr _

            _ × v'' = successful (eval γ' (successful (desugFwd' s')) true)
            src = render (pretty s)
            srcExp = show (erase s)
```

Currently, desugaring keeps the annotation type as arbitrary. As per your comment above, should desugaring be changed to have it set to `Unit` instead, and then we implement two orthogonal functions for setting it to `Bool` or `Vertex`?

**Comment by min-nguyen** [comment]
Unrelated: should `desugFwd` rather be called `desug`, to be consistent with `eval` ?

**Comment by rolyp** [comment]
@min-nguyen Re. your `testWithSetup` question, good point yes `desugar` requires `a` to be an `Ann` and `testWithSetup` assumes the surface program is annotated with `Bool` from the beginning (whereas above I suggested `desugar` returned something of type `Expr Unit`, which it can do but doesn’t here). 

Maybe the easiest thing for now is to take the desugared term of type `Expr Bool` and use `mapM` to replace every `Bool` annotation by the result of a fresh `alloc`, to get something of type `Expr Vertex`, which can then be used for the second pipeline above.

**Comment by min-nguyen** [comment]
We can have a chat this afternoon, but here's what I have.

```haskell

type Fresh a = State Int a

freshVertex :: Fresh Vertex
freshVertex = do
   s <- get
   put (s + 1)
   pure (Vertex (show s))

alloc :: forall a. Expr a -> Fresh (Expr Vertex)
alloc (Var x) = pure $ Var x
alloc (Op op) = pure $ Op op
alloc (Int _ n) = do
   α <- freshVertex
   pure $ Int α n
alloc (Float _ n) = do
   α <- freshVertex
   pure $ Float α n
alloc (Str _ str) = do
   α <- freshVertex
   pure $ Str α str
alloc (Record _ xes) = do
   α <- freshVertex
   Record α <$> traverse alloc xes
alloc (Dictionary _ ees) = do
   α <- freshVertex
   Dictionary α <$> traverse (traverse alloc) ees
alloc (Constr _ c es) = do
   α <- freshVertex
   Constr α c <$> traverse alloc es
alloc (Matrix _ e1 (x × y) e2) = do
   α <- freshVertex
   Matrix α <$> alloc e1 <*> pure (x × y) <*> alloc e2
alloc (Lambda σ) = Lambda <$> allocElim σ
alloc (Project e x) = Project <$> alloc e <*> pure x
alloc (App e e') = App <$> alloc e <*> alloc e'
alloc (Let (VarDef σ e) e') = Let <$> (VarDef <$> allocElim σ <*> alloc e) <*> alloc e'
alloc (LetRec ρ e) = LetRec <$> traverse allocElim ρ <*> alloc e
alloc (Sugar s e) = Sugar s <$> alloc e

allocElim :: forall a. Elim a -> Fresh (Elim Vertex)
allocElim (ElimVar x κ) = ElimVar x <$> allocCont κ
allocElim (ElimConstr m) = ElimConstr <$> traverse (allocCont) m
allocElim (ElimRecord xs κ) = ElimRecord xs <$> allocCont κ
allocElim (ElimSug sσ κ) = ElimSug sσ <$> allocElim κ

allocCont :: forall a. Cont a -> Fresh (Cont Vertex)
allocCont ContNone = pure ContNone
allocCont (ContExpr e) = ContExpr <$> alloc e
allocCont (ContElim σ) = ContElim <$> allocElim σ
```

**Comment by rolyp** [comment]
@min-nguyen Cool, thanks :) I think we probably want a `Traversable` instance for `Expr` etc so that we can avoid the `alloc` boilerplate and just use `traverse (const freshVertex)`.  A quick search suggests that `Foldable` and `Traversable` should now be derivable in PureScript but I tried it and it complains that “instances of this typeclass are not derivable”. Let’s look into this later..

**Comment by rolyp** [comment]
Ok, it looks like deriving `Foldable`/`Traversable` was merged into `purs` on 30 Sep 2022 (https://github.com/purescript/purescript/pull/4392) and we’re currently using 0.15.4, which  according to `npm` was published “a year ago”. So upgrading PureScript to 0.15.10 (say) should pull that in.

**Comment by rolyp** [comment]
I’ll have a go at bumping the PureScript version and merging that to `develop`.

**Comment by min-nguyen** [comment]
I actually tried the traversable thing to start off with, (which is a nice one liner), but it requires Expr to be an Applicative (implement `pure`) which I wasn't sure about.

**Comment by min-nguyen** [comment]
Think this should be done with that last merge.
