### ISSUE TITLE
Graph evaluation semantics

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#637]
New `eval` implementation which discards annotation on expression and environment and uses the `Addr` annotations to produce a dependence graph, using the definition currently in the paper, along with a `Value`similarly annotated with `Addr`.

**Comment by rolyp** [comment]
I think we touched on this problem the other day.

The `allocate` interface I proposed (that allocates a fresh $\alpha$ w.r.t. a particular $G$) feels problematic. The “natural” implementation which allocates $\alpha$ deterministically by returning  $|\mathsf{dom}(G)| + 1$ converted to a vertex (string) treats vertices as “positional” indices within a particular graph. That means graphs can’t be constructed independently and then merged later, since their vertices will overlap. At the moment we don’t do that – we thread a single graph through the evaluation – but it still feels like the wrong idea (I’m afraid I don’t have a more sophisticated argument!).

It probably makes more sense to have a global pool of addresses (essentially a global heap $\chi$) which we use to allocate vertices. The same allocation procedure can be used, i.e. return $|\chi| + 1$ converted to a string, but now the heap will be shared by all graphs.

I guess this means the graph `eval` will live in some kind of `StateT` monad augmented with an `alloc` method, and that `allocate` no longer belongs on the `Graph` class.

**Comment by rolyp** [comment]
@min-nguyen Some thoughts on how to get started with the graph semantics. What we want is a separate implementation of `Eval.purs`, e.g. `EvalGraph.purs`, with a slightly different type signature. 

I suggest starting with `match` and `matchMany`, since that will defer having to change the effect signature to accommodate `alloc`. It will have a type along the lines of:

```purescript
match :: Val Vertex 
      -> Elim Vertex 
      -> MayFail (Env Vertex × Cont Vertex × Set Vertex)
```
(The output annotation from the current version of `match` is replaced by a set of vertices, and the `Match` output is no longer needed at all.)

- `top` will correspond to the empty set of vertices (i.e. that particular `match` establishes no dependencies on parts of `v`).
- $\wedge$ will correspond to set union, although as we will always be inserting a single vertex, we can probably use `insert` instead.

Once that’s done we can start thinking about the signature of `eval`.

**Comment by min-nguyen** [comment]
@rolyp  Does this task come before https://github.com/explorable-viz/fluid/issues/636 ?

**Comment by rolyp** [comment]
@min-nguyen I think they’re independent (although #636 will be needed in order to test #637 in earnest).
