### ISSUE TITLE
Initial graph optimisation experiments

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#663]
We have noticed severe performance problems in our graph implementation. Eddie’s suggestion of switching to a `State`-based approach doesn’t seem to improve things significantly so some investigation is required.

### `Graph.purs`
- [x] Fix `Graph.purs` for obvious inefficiencies with `union`/intermediate graphs 
- #668
- #673
- #674

#### Easy optimisations that might help get test cases working (even if performance still sucks)
- #671

### Underlying `Foreign.Object` implementation
- [x] **[Roly]** Trace `_copyST` with size of objects
- #670
- #669
- [x] Check whether any methods used by `GraphImpl` are potential problems

**Comment by rolyp** [comment]
Carried out some initial experiments and created a bunch of new tasks to continue investigation.
