### ISSUE TITLE
Hungarian Algorithm Purescript Implementation

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#756]
As a part of issues #733 and #752 we have identified a strong candidate motivating example. The algorithm solves the "assignment problem" and is used as a core component of the model we were considering implementing in issue #752 

We will need to implement it in fluid, but that's not necessarily easy because we don't have proper developer tools for fluid left. The first iteration is to build a naive version of the (matrix interpretation) of the algorithm in purescript. This has to be done without monads/explicit use of typeclasses.

Once the first iteration is done, we need to simplify the implementation down, potentially changing some types, and setting things up so we can more easily translate it into fluid.

The first iteration is based off a reference haskell implementation, which makes use of monads like STRef which isn't helpful, so migrating it has taken some time. The algorithm is broken into 6 steps which will form the current set of subtasks:

- [ ] Purescript implementation 1
  - [x] Step 1
  - [x] Step 2
  - [x] Step 3
  - [ ] Step 4
  - [ ] Step 5
    - [ ] 5a
  - [ ] Step 6

**Comment by rolyp** [comment]
Dropped for the time being as looking to complex and somewhat off-piste for what we currently need.
