### ISSUE TITLE
Broken infix notation for Boolean operators

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#785]
Using ``or`` and `and` in infix notation in fluid seems inconsistent. The lengthy predicate in, for example `cost-matrix.fld` allows us to move the leading `or` to be infix (in the conditional), but does not allow you to move all occurrences of `and` and `or` into infix. That is, the following works:
``if ((and (n == 1) (m == 1)) `or` (and ((abs n m) <= window) (not (or (n == 1) (m == 1)))))
                       then FNum 0
                       else Infty``
But this does not:
``if ((and (n == 1) (m == 1)) `or` (and ((abs n m) <= window) (not ((n == 1) `or` (m == 1)))))
                       then FNum 0
                       else Infty ``

As far as I can tell, infix `and`'s don't seem to work at all

**Comment by rolyp** [comment]
Doesn’t seem to be an issue after all.
