### ISSUE TITLE
Replace `TraceRow` and `GraphRow` by maps

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#794]
There isn’t much benefit in using records for the benchmarking results, especially if you look at the `Show` instance for `BenchAcc`, or the way `testGraph` has to accumulate lots of local variables in order to return a record at the end. It would also be useful to be able to dynamically disable/enable particular benchmarks. Replace the record types by maps from benchmark names to numbers, and use a `Writer` to accumulate benchmark results in `testTrace` and `testGraph`.

**Comment by min-nguyen** [comment]
..

**Comment by min-nguyen** [comment]
Benchmarking code should be looking a lot better now hopefully.

The type `BenchRow` is now a `Map` that stores all the timings for the trace-based and graph-based tests:
```haskell
newtype BenchRow = BenchRow (Map String Number)

instance Semigroup BenchRow where
   append (BenchRow row1) (BenchRow row2) = BenchRow (unionWith (+) row1 row2)

instance Monoid BenchRow where
   mempty = BenchRow
      (fromFoldable [ ("Trace-Eval" × 0.0), ("Trace-Bwd" × 0.0), ("Trace-Fwd" × 0.0), ("Graph-Eval" × 0.0), ("Graph-Bwd" × 0.0), ("Graph-Fwd" × 0.0), ("Graph-BwdDual" × 0.0), ("Graph-BwdAll" × 0.0), ("Graph-FwdDual" × 0.0), ("Graph-FwdAsDeMorgan" × 0.0) ])

```
The wrapper function `bench` records and sums all the timings (for the same entry name) in the `Writer` monad.
```haskell
bench :: forall m a. MonadEffect m => MonadWriter BenchRow m => String -> (Unit -> m a) -> m a
bench name prog = do
   t1 <- preciseTime
   r <- prog unit
   t2 <- preciseTime
   tell (BenchRow $ singleton name (tdiff t1 t2))
   pure r

-- | For example, this will add on a single benchmark time to the entry "Trace-Eval"
testTrace s γ { δv, bwd_expect, fwd_expect } =
   ...
   let e = desug.fwd s
   { gc: GC eval, v } <- bench "Trace-Eval" $ \_ ->  traceGC (erase <$> γ) e
   ...
```
And then in `test`, we can run the `WriterT` monad once and divide by the number of runs:
```haskell
test ∷ forall m. File -> ProgCxt Unit -> TestConfig -> (Int × Boolean) -> AffError m BenchRow
test file progCxt tconfig (n × is_bench) = do
   gconfig <- initialConfig progCxt
   s <- open file
   testPretty s
   _ × row_accum <- runWriterT
      ( replicateM n $ do
           testTrace s gconfig.γ tconfig
           testGraph s gconfig tconfig is_bench
      )
   pure $ row_accum `divRow` n
```

**Comment by rolyp** [comment]
This is much better – thanks! This should more flexible going forward. 

I got rid of the repeated string literals by requiring `BenchAcc` to be a non-empty array (with an unsafe cast in `Benchmark.main`). I was hoping that would allow the `Monoid` instance for `BenchRow` to go away entirely, but `Writer` requires a monoid, so the instance remains (but the unit can now just be the empty map, with no need to mention the keys).
