### ISSUE TITLE
Compute sinks and sources on graph construction

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#820]
Our graphs are immutable so I think it plausibly makes sense to compute sources/sinks once at construction time. The advantage of doing this is that we can push these into the graph-building overhead and then use them freely during slicing etc without having to consider whether there is an associated cost.

**Comment by JosephBond** [comment]
I agree with this, it seems very similar to my initial notion of computing the inputs and outputs at evaluation time. Whilst it would, I presume, lose us a tiny bit of performance on evaluation, I'd be more than happy to pay that cost. Is the intention to still use sources and sinks as our notions of inputs and outputs?

**Comment by rolyp** [comment]
Ok good. I think it’s clear that source implies output (where “outputs” is the ambient set used for complementing), but I think we already know that output does not imply source (since we want to slice values which may have parts depended on by other parts). Need to check now whether that is a potential issue for De Morgan too.
