### ISSUE TITLE
Fluid code for Example

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#846]
- [x] Source code for linked inputs example
- [x] Output to be bubble chart, rather than table
- [ ] Incorporate into paper as single text file
- [ ] Use `datasetAs` to import each input?

### Rework example to make more realistic/understandable:
- [x] Variable names `all_waters`, `all_countries` could be shortened for legibility (e.g. `countries`)
- [x] `cities` field (list of strings) doesn’t display properly – maybe split into separate records
- [x] `country.farms * 3` looks odd

**Comment by rolyp** [comment]
Dropped DTW as motivating example.

**Comment by rolyp** [comment]
Reopened but retargeted to `water.fld` example.

### Previously
Include Fluid code for DTW example (library + user code) into paper.

- [ ] Shorten variable names (where readability not compromised)
- [ ] `extractPath` can lose internal helper
- [ ] Assigned to paired variables can become a pair assignment
- [ ] Separate figures `fnum.fld` and `dtw.fld` (perhaps include final user code into same figure as `dtw.fld`)

**Comment by rolyp** [comment]
Adding todos to make example code more perspicuous.

**Comment by JosephBond** [comment]
Regarding variable names, is whatever name I choose for the 2 lists of records visible to the rest of the program? ie can I remove the arguments such as `country_water`, which takes in the lists of records as part of its input. Is it fine to treat the 2 linkedInputs variables as global for the rest of the program?

**Comment by JosephBond** [comment]
Okay that works for now, does clean things up quite dramatically.
