### ISSUE TITLE
0.7.4 website infrastructure

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#924]
See also:
- #1150 
- #1153 

Done/dropped:
- [x] New top-level URL `f.luid.org/0.6.1/`, with snapshot of that version for posterity
  - [x] `v0.6.1.sh` to bundle 0.6.1 release as `.zip`
  - [x] Verify zip archive (when extracted) runs as static website
  - [x] `0.6.1.yml` workflow which unzips and publishes using `gh-pages`
- [x] Rename `App.purs` to `Website.purs`
- [x] Lose intermediate `app` folder in `dist`
- [x] Rename `app.js` to `fluid.js`
- [x] Rename `build-app` target to `build-website` (and similarly for `serve-app`)
- [x] Rethink `0.3.1` and `0.6.1` as static paths built by `build-website.sh`
  - [x] New `build-website.sh` to build `Website` entry point and unzip `0.3.1.zip` and `0.6.1.zip` to `dist`
  - [x] `build-website` target to call `build-website.sh`
  - [x] Drop `0.3.1-typescript.yml` and `0.6.1.yml` 
- [x] Empty path as `“”` doesn’t work
- [x] `build.yml` to run `yarn build` too, otherwise `dist/test` doesn’t exist (and zero tests run == success!)
- [x] Fix code font in Firefox (Fira Code rejected by sanitiser)
- [x] Merge `release` to `website-update`
- <s>`v0.3.1` link as relative path?</s>
- [x] #1101
- [x] #1110
- [x] Some cleanup of `index.html`
  - [x] `./script/util/copy-static.sh` only needed at `build.sh` level; don’t copy static files to each `$1` subdir
  - [x] `./script/bundle.sh test Test.Test` doesn’t need `index.html` – omit this step?
  - [x] `yarn bundle-bench` needs one, but can be empty
- [x] Each “website” (`test`, `bench`, `website`, `ESOP-artifact`) as separate subfolder of `dist`
- [x] Each `Standalone` in `example` folder of website
- [x] Lose `website/website`
- [x] Extract commonality from `bundle-esop2025-artifact`, `bundle-fluid-org` and `bundle-misc`
- [x] Organise `Standalone` folder into websites
- [x] Common location for `toLispCase`
- [x] Link to `0.6.1` from landing page
- [x] `test-website-all.sh` to fail on tests that don’t have corresponding website
- [x] Version number on landing page
- <s>`build-website` and `test-website` to support “websites” without `index.html` entrypoint?</s> :x: maybe later
- [x] Top-level examples in `FluidOrg`:
  - [x] NonRenewables (landing page) + source code
  - [x] Convolution (wrap/no-wrap) + source code
  - [x] MovingAverage + source code
- [x] Experiment with JavaScript/AJAX approach to shared HTML
- [x] `build-website.sh` to support additional `.html` beyond pages accompanying Fluid examples
- [x] `bundle-website` to only run `bundle-page` on `.purs` files
- <s>`on-bundle.sh` hook, obviating need for `bundle-fluid-org.sh`?</s> leave for now

**Comment by rolyp** [comment]
@RaoOfPhysics Should we think about using Reveal to author this page?

**Comment by RaoOfPhysics** [comment]
It’s not a bad idea but I have some reservations. At some stage, as Fluid’s documentation starts being built up, the home page will have to serve three kinds of purposes:

1. A brief (interactive) intro to Fluid, with maybe one example.
2. Documentation!
3. A showcase of examples. This can be tied to documentation, of course. But this last one is the most obvious case for using a presentation format.

**Comment by rolyp** [comment]
Font-wise, I like how `distill.pub` looks on my Mac. Chrome describes the rendered font as
> Family name: .SF NS
> PostScript name: .SFNS-Regular_wdth_opsz110000_GRAD_wght

which [Reddit](https://www.reddit.com/r/identifythisfont/comments/18dafl3/a_font_named_sf_ns_text_from_my_old_computer/) claims is Lucida Grande.

**Comment by rolyp** [comment]
Let’s dovetail as much of this issue with explorable-viz/fluid-examples#36 as possible. For example, let’s aim to have any examples we want to use at the Summer School hosted on the website, and maybe we can use the website to introduce the project/collaborators etc too.

This will also help with explorable-viz/research-strategy#95 and other proposals as the website will have more up-to-date examples/project goals/project background.

**Comment by rolyp** [comment]
### Organising principles for website and how scripts build the various parts

- Prior versions of website only link “backwards” (to earlier versions)
- Each `Standalone/ExName` (one or more figures + text) has its own `f.luid.org/ex-name/index.html`
- Individual `/ex-name/index.html` files may reference each other, and may correspond to:
  - Web artifacts to accompany paper submissions
  - Slides to use in presentations
  - Examples for website
- `build-XXX-artifact.sh` builds the artifact main page for a submission to XXX conference
- `build-website.sh` (previously `build-app`) builds the `f.luid.org` pages
- Each script builds the required examples from `Standalone` using `build-standalone.sh`
- `build-standalone-all.sh` builds all such examples found in `Standalone` (maybe no longer required)
- Each “website” to have a subfolder under `web`?

**Comment by rolyp** [comment]
Extracted content-related tasks to #1150. Will consider this task done once there is infrastructure to support multiple websites, each with multiple content pages, some of them just `.html`, others with associated `.purs` files providing Fluid visualisations.
