### ISSUE TITLE
Realign benchmarks with current paper plan

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#965]
After discussion today decided provisionally on the following:

- Aggregate test cases into following 3 categories:
  - graphics examples (as examples that aren’t obviously highly parallel)
  - matrix cases (various convolution cases, DTW – not hard to justify and convolution cases were in prior work)
  - linked outputs examples (work to do here – currently not benchmarked)
  - smaller language/slicing tests **won’t** be included, except potentially in the trace/graph overhead comparison
- We can’t easily compare linked inputs performance with previous approach, so omit those
- We’ll only end up with ~8 test cases + linked outputs, so we could report aggregate information and individual values
- Revisit benchmarks to align with structure and names proposed in explorable-viz/icfp2024#407

See also:
explorable-viz/icfp2024#407

**Comment by rolyp** [comment]
Dropping back to Planned for now (i.e. still in scope but not priority).

**Comment by rolyp** [comment]
Renamed from “Aggregate statistics for classes of test case” (which this now subsumes).
