### ISSUE TITLE
Out-of-date README and missing file contents

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#973]
- [x] `yarn build-tests` $\to$ `yarn build`
- [x] `yarn tests` $\to$ `yarn test`
- [x] `yarn tests-browser` $\to$ `yarn test-browser`
- [x] Delete `app-tests` instruction
- [x] Extract artefact-related notes to `icfp2024-artefact.md`
- Fix code toggles (check in Chrome)
  - [x] Undo commented code in `App.purs`
  - [x] `bar-chart.fld` and `line-chart.fld` still not loaded
  - [x] `renewables.fld` not loaded
  - [x] Replace prettyprinted views by file views
- [x] Check in Safari

From @RaoOfPhysics:

> I am running Kubuntu 23.10, for info.
> I started off by installing yarn and got v1.22.19 to work.
> I cloned the fluid repo, cd’d into it and ran yarn install. Everything seemed fine.
> I then tried running yarn build-tests, yarn tests, yarn build-app-tests and yarn app-tests, all of which said the respective commands weren’t found.
> I decided to skip the tests and run yarn serve-app. First error I got was that npx wasn’t found on my system. It isn’t listed as a requirement. So I installed npm and then ran npm install -g npx.
> It then gave me an error saying html-serve couldn’t be installed, so I installed it manually with npm install -g html-serve.
> After this, running yarn serve-app worked and I finally got it in the browser (Firefox).

Also:
> None of the toggles show anything.

**Comment by RaoOfPhysics** [comment]
Thanks, Roly! Will create an issue next time!
